/* Open Your Eyes — Field Notes. The real history behind everyone you meet.
 * A note unlocks when you first speak to that person. `kind` says honestly what each one is. */
(function () {
  'use strict';
  const NOTES = [
    { id: 'about', kind: 'About this story', title: 'The Plane at 5:12', always: true, text: [
      'This is a work of fiction. It borrows its shape from two places. Jean-Paul Sartre\'s 1944 play No Exit (Huis clos) opens with a valet showing a newly dead man into a hotel room with Second Empire furniture, three sofas, a bronze on the mantel and no mirrors, and it ends with the line "Hell is other people." The Outer Limits (1963–65) opened and closed each episode with an unseen narrator, the "Control Voice." The narrator here is an homage, written fresh.',
      'Real historical people appear as ghosts. Their lines are imagined, but the facts they tell are drawn from the historical record. Where a character is a composite, the note says so.'
    ]},
    { id: '512', kind: 'Real history', title: '5:12 a.m.', always: true, text: [
      'The great San Francisco earthquake struck on April 18, 1906, at about 5:12 in the morning. The shaking lasted under a minute; the fires that followed burned for three days, destroyed roughly 80 percent of the city, and killed an estimated 3,000 people.',
      'Every April 18th, a commemoration is still held at Lotta\'s Fountain on Market Street at 5:12 a.m.'
    ]},
    { id: 'valet', kind: 'Invented', title: 'The Valet', text: ['A homage to the Valet in Sartre\'s No Exit, who shows each new arrival to the room and cannot tell them why there are no windows.'] },
    { id: 'nana', kind: 'Invented', title: 'Nana', text: ['The narrator\'s grandmother, from the Excelsior District.'] },
    { id: 'norton', kind: 'Real person', title: 'Joshua Norton, "Emperor Norton" (c. 1818–1880)', text: ['A businessman ruined by a failed rice deal, Norton proclaimed himself Emperor of the United States in 1859. The city humored him: restaurants fed him, and his self-printed currency was often honored. In 1872 he decreed that a bridge be built across the bay. Up to 30,000 people are said to have attended his funeral.'] },
    { id: 'bummer', kind: 'Real animals', title: 'Bummer and Lazarus', text: ['Two stray dogs famous in 1860s San Francisco for hunting rats together. Newspapers followed them closely and they were often linked to Emperor Norton, though they were not his. Lazarus died in 1863 and Bummer in 1865; Mark Twain wrote about Bummer\'s death.'] },
    { id: 'twain', kind: 'Real person', title: 'Mark Twain (1835–1910)', text: ['Samuel Clemens worked as a reporter for the San Francisco Morning Call in 1864. The line "The coldest winter I ever spent was a summer in San Francisco" is widely attributed to him, but there is no evidence he said it.'] },
    { id: 'felt', kind: 'Real person', title: 'W. Mark Felt (1913–2008)', text: ['Associate Director of the FBI and the secret source "Deep Throat" who guided Washington Post reporters Bob Woodward and Carl Bernstein during Watergate. He revealed his identity in 2005, at 91. The Union Square Garage (1942) is often described as the first underground parking garage in the world.'] },
    { id: 'ralston', kind: 'Real person', title: 'William Ralston (1826–1875)', text: ['Founder of the Bank of California and builder of the original Palace Hotel, once the largest hotel in the West, with 755 rooms and hydraulic elevators called "rising rooms." His bank failed in August 1875; the next day he drowned while swimming off North Beach. The hotel opened that October. It burned in 1906 and was rebuilt in 1909.'] },
    { id: 'levi', kind: 'Real person', title: 'Levi Strauss (1829–1902)', text: ['A dry-goods wholesaler who came to San Francisco in 1853. In 1873 he and Reno tailor Jacob Davis patented copper-riveted work pants, the first blue jeans.'] },
    { id: 'fireman', kind: 'Composite', title: 'A fireman of 1906', text: ['A composite. The earthquake broke the water mains, so firefighters dynamited buildings to create firebreaks. Fire Chief Dennis Sullivan was fatally injured in the quake itself. Lotta\'s Fountain, a gift of the actress Lotta Crabtree in 1875, served as a message board for the missing.'] },
    { id: 'lee', kind: 'Composite', title: 'Mrs. Lee, of Taishan', text: ['A composite. Most early Chinese immigrants to California came from the Siyi ("Four Counties") region of Guangdong province, especially Taishan (Toisan). The Chinese Exclusion Act of 1882 barred most Chinese immigration. From 1910 to 1940 many arrivals were detained at the Angel Island Immigration Station, where detainees carved poems into the barrack walls. The poems are still there.'] },
    { id: 'brannan', kind: 'Real person', title: 'Sam Brannan (1819–1889)', text: ['In May 1848 he announced the gold discovery by waving a bottle of gold dust in Portsmouth Square, shouting "Gold! Gold from the American River!" He had already cornered the market in mining supplies and became California\'s first millionaire. He died nearly penniless.'] },
    { id: 'giannini', kind: 'Real person', title: 'A. P. Giannini (1870–1949)', text: ['Founded the Bank of Italy in North Beach in 1904 to serve working immigrants. During the 1906 fire he moved the bank\'s gold out of the city in a produce wagon and soon resumed lending from a plank across two barrels on the waterfront. The bank became Bank of America.'] },
    { id: 'dimaggio', kind: 'Real person', title: 'Joe DiMaggio (1914–1999)', text: ['The son of a Sicilian fisherman, raised in North Beach. With the San Francisco Seals of the Pacific Coast League he hit safely in 61 straight games in 1933; with the Yankees he set the major-league record of 56 in 1941.'] },
    { id: 'ferl', kind: 'Real person', title: 'Lawrence Ferlinghetti (1919–2021)', text: ['Poet and co-founder of City Lights Bookstore (1953). He published Allen Ginsberg\'s Howl and Other Poems in 1956, was arrested on obscenity charges, and was acquitted in 1957 in a landmark free-speech ruling. He died at 101.'] },
    { id: 'opp', kind: 'Real person', title: 'J. Robert Oppenheimer (1904–1967)', text: ['Theoretical physicist who taught at UC Berkeley and led the Los Alamos laboratory that built the first atomic bombs. Components of the "Little Boy" bomb left Hunters Point aboard the USS Indianapolis on July 16, 1945, the day of the Trinity test.'] },
    { id: 'ginsberg', kind: 'Real person', title: 'Allen Ginsberg (1926–1997)', text: ['First read his poem Howl at the Six Gallery, 3119 Fillmore Street, on October 7, 1955, a night often called the birth of the Beat movement. The poem finished in this game is an original written for it, not a Ginsberg poem.'] },
    { id: 'kerouac', kind: 'Real person', title: 'Jack Kerouac (1922–1969)', text: ['Attended the Six Gallery reading, collected money for wine, and cheered the readers on with shouts of "Go!" He fictionalized the night in The Dharma Bums (1958).'] },
    { id: 'soldier', kind: 'Composite', title: 'A soldier at Fort Mason', text: ['A composite. The San Francisco Port of Embarkation at Fort Mason shipped more than 1.6 million troops to the Pacific during World War II. "Golden Gate in \'48" was a hopeful soldiers\' slogan.'] },
    { id: 'sutro', kind: 'Real person', title: 'Adolph Sutro (1830–1898)', text: ['Engineer of the Sutro Tunnel, which drained the Comstock Lode mines in Nevada, and mayor of San Francisco (1895–97). His Sutro Baths opened in 1896 with seven pools filled by the tide. The building burned in 1966; the ruins remain at Lands End.'] },
    { id: 'ussf', kind: 'Composite', title: 'A sailor of the USS San Francisco', text: ['A composite. In the Naval Battle of Guadalcanal (November 1942) the cruiser was hit many times; Rear Admiral Daniel Callaghan and Captain Cassin Young were killed. The ship\'s shell-pierced bridge wings stand as a memorial at Lands End.'] },
    { id: 'iron', kind: 'Composite', title: 'An ironworker of the Golden Gate', text: ['A composite. The bridge (1933–37) was the first built with a safety net slung beneath it; 19 men who fell into it and survived formed the "Halfway to Hell Club." On February 17, 1937, a scaffold fell through the net and ten workers died.'] },
    { id: 'buffalo', kind: 'Composite', title: 'A trooper of the Ninth Cavalry', text: ['A composite. Black "Buffalo Soldiers" of the 9th Cavalry and 24th Infantry were stationed at the Presidio around 1900 and patrolled Yosemite and Sequoia before the National Park Service existed. Captain Charles Young served as acting superintendent of Sequoia in 1903.'] },
    { id: 'soldado', kind: 'Composite', title: 'A soldado de cuera', text: ['A composite. Juan Bautista de Anza led about 240 settlers from Sonora and Sinaloa in New Spain to Alta California in 1775–76. Lieutenant José Joaquín Moraga founded the Presidio of San Francisco in September 1776. "Soldados de cuera" wore protective leather coats.'] },
    { id: 'bridges', kind: 'Real person', title: 'Harry Bridges (1901–1990)', text: ['Longshore leader of the 1934 West Coast waterfront strike. On July 5, 1934, "Bloody Thursday," police killed two men near the Embarcadero. The longshore union still stops work on the coast each July 5 in their memory.'] },
    { id: 'niantic', kind: 'Composite', title: 'A sailor off the Niantic', text: ['A composite. Hundreds of Gold Rush ships were abandoned when crews ran for the mines. The Niantic was hauled ashore and used as a warehouse and hotel until the fire of 1851; the shoreline was later filled in around such ships. Remains of dozens lie under the Financial District.'] },
    { id: 'hearst', kind: 'Real person', title: 'William Randolph Hearst (1863–1951)', text: ['Born in San Francisco, he took over the San Francisco Examiner in 1887 and built a publishing empire. In 1889 his paper had a grizzly captured and brought to the city.'] },
    { id: 'monarch', kind: 'Real animal', title: 'Monarch the grizzly (d. 1911)', text: ['Captured in 1889 for the Examiner and displayed in San Francisco for over twenty years. He is widely described as the model for the bear on the California state flag. His mounted body is held by the California Academy of Sciences.'] },
    { id: 'claude', kind: 'Real animal', title: 'Claude the albino alligator', text: ['A much-loved resident of the California Academy of Sciences in Golden Gate Park from 2008 until his death in 2020.'] },
    { id: 'digger', kind: 'Composite', title: 'A Digger, 1967', text: ['A composite. The Diggers, a Haight-Ashbury community-action group, served free food daily in the Panhandle. After the Summer of Love, residents staged a mock "Death of the Hippie" funeral in October 1967.'] },
    { id: 'robin', kind: 'Real person', title: 'Robin Williams (1951–2014)', text: ['Comedian and actor who made San Francisco his home. Mrs. Doubtfire (1993) was filmed at a Victorian at Steiner and Broadway in Pacific Heights, where fans still leave notes and flowers.'] },
    { id: 'pleasant', kind: 'Real person', title: 'Mary Ellen Pleasant (c. 1814–1904)', text: ['Entrepreneur and abolitionist who arrived in 1852 and helped many people escape slavery. In the 1860s she sued a streetcar company for refusing her a ride; she won in the lower court, and the verdict was overturned on appeal. Eucalyptus trees she planted still stand at Octavia and Bush.'] },
    { id: 'jazz', kind: 'Composite', title: 'A musician from the Fillmore', text: ['A composite. Wartime shipyard jobs drew tens of thousands of Black Southerners to San Francisco, and the Fillmore became the "Harlem of the West," with after-hours clubs like Jimbo\'s Bop City. Urban "redevelopment" later demolished much of the neighborhood.'] },
    { id: 'jerry', kind: 'Real person', title: 'Jerry Garcia (1942–1995)', text: ['Guitarist of the Grateful Dead, born in San Francisco and raised partly in the Excelsior District. The band lived at 710 Ashbury Street in 1966–68.'] },
    { id: 'milk', kind: 'Real person', title: 'Harvey Milk (1930–1978)', text: ['Ran Castro Camera at 575 Castro Street and in 1977 became the first openly gay person elected to public office in California. On November 27, 1978, he and Mayor George Moscone were assassinated at City Hall.'] },
    { id: 'tomas', kind: 'Composite', title: 'Tomás', text: ['A composite. The NAMES Project AIDS Memorial Quilt was begun in San Francisco in 1987. Each panel measures three by six feet. At its first display on the National Mall that October it was larger than a football field.'] },
    { id: 'elder', kind: 'Composite', title: 'An elder of the Yelamu', text: ['A composite, written with care. The Ramaytush Ohlone are the original people of the San Francisco Peninsula; the Yelamu were the group whose villages, including Chutchui near Mission Creek, stood in present-day San Francisco. Thousands of Native people are buried at Mission Dolores. Ohlone people are living communities today; the Association of Ramaytush Ohlone works on their behalf.'] },
    { id: 'settler', kind: 'Composite', title: 'A settler from Sonora', text: ['A composite of the Anza expedition families. On the expedition\'s first night in October 1775, Manuela Piñuelas gave birth to a son and died of complications. Mission San Francisco de Asís (Mission Dolores) was founded in 1776.'] },
    { id: 'mays', kind: 'Real person', title: 'Willie Mays (1931–2024)', text: ['The "Say Hey Kid" moved west with the Giants in 1958 and played at Seals Stadium and Candlestick Park. Oracle Park\'s address is 24 Willie Mays Plaza, after his uniform number.'] },
    { id: 'gunner', kind: 'Composite', title: 'A coast artilleryman', text: ['A composite. Battery Davis at Fort Funston mounted two 16-inch guns with a range of about 25 miles. They were never fired at an enemy.'] },
    { id: 'gene', kind: 'Real person', title: 'Gene Roddenberry (1921–1991)', text: ['Creator of Star Trek, which places Starfleet Headquarters and Starfleet Academy in San Francisco. The 1967 episode "Mirror, Mirror" introduced an alternate universe of the same crew, subtly wrong.'] },
    { id: 'refugee', kind: 'Composite', title: 'A refugee of 1906', text: ['A composite. After the fire, relief agencies built about 5,600 small "earthquake shacks" in city parks, painted park-bench green, which residents could buy for small monthly payments. Many were later moved; some survive in Bernal Heights.'] },
    { id: 'nurse', kind: 'Composite', title: 'A nurse of 1918', text: ['A composite. During the 1918 influenza pandemic San Francisco required masks in public; violators were fined or jailed, and an Anti-Mask League formed in 1919. San Francisco General Hospital is the city\'s only Level I trauma center.'] },
    { id: 'indy', kind: 'Composite', title: 'A sailor of the Indianapolis', text: ['A composite. The USS Indianapolis left Hunters Point on July 16, 1945, carrying atomic bomb components to Tinian. On July 30 it was sunk by a Japanese submarine; of about 1,195 men aboard, 316 survived.'] },
    { id: 'welder', kind: 'Composite', title: 'Odessa, a shipyard welder', text: ['A composite. The Hunters Point Naval Shipyard hired thousands of Black workers from Louisiana, Texas and elsewhere in the South during World War II, and the Bayview–Hunters Point community grew around it.'] },
    { id: 'spy', kind: 'Real person', title: 'Grigory Kheifets (1899–1984)', text: ['A Soviet intelligence officer posted to the Soviet consulate in San Francisco during World War II, who sought information about atomic research at Berkeley. His scenes here are fictional.'] },
    { id: 'clark', kind: 'Real person', title: 'Dwight Clark (1957–2018)', text: ['49ers receiver who made "The Catch," a leaping touchdown grab from Joe Montana with 58 seconds left in the NFC Championship Game at Candlestick Park on January 10, 1982.'] },
    { id: 'walsh', kind: 'Real person', title: 'Bill Walsh (1931–2007)', text: ['Head coach of the 49ers from 1979 to 1988 and winner of three Super Bowls. He famously scripted his first 15 offensive plays before each game.'] }
  ];
  window.OYE_NOTES = NOTES;
})();
